#!/bin/bash

set -eou pipefail

VPASSMAN_PROJECT_BASE_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

export VPASSMAN_PROJECT_BASE_DIR
export VPASSMAN_EXISTING_READABLE_FILE="${VPASSMAN_PROJECT_BASE_DIR}/dummy"
export VPASSMAN_MYCAT_EXE_PATH="${VPASSMAN_PROJECT_BASE_DIR}/src-mycat/main"

export VPASSMAN_TEST_MOUNTPOINT_LOCATION_REGULAR="${VPASSMAN_PROJECT_BASE_DIR}/mountpoint-regular"
#mkdir -p "$VPASSMAN_TEST_MOUNTPOINT_LOCATION_REGULAR" || echo ""

export SPECIAL_MOUNT_DIRNAME=$'mountpoint_spec_chars_start\\ \t*?\ndone'
export VPASSMAN_TEST_MOUNTPOINT_LOCATION_SPECIALCHARS="${VPASSMAN_PROJECT_BASE_DIR}/${SPECIAL_MOUNT_DIRNAME}"

VPASSMAN_MOUNTPOINT="${VPASSMAN_MOUNTPOINT:=/tmp/test_only_default_vpassman_mountpoint}"
export VPASSMAN_MOUNTPOINT

if [ ! -d "${VPASSMAN_MOUNTPOINT}" ]; then
	mkdir "${VPASSMAN_MOUNTPOINT}"
fi

#mkdir -p "$VPASSMAN_TEST_MOUNTPOINT_LOCATION_SPECIALCHARS"

export VPASSMAN_TESTHELPER_SUID_MYCAT_EXE_PATH="${VPASSMAN_PROJECT_BASE_DIR}/src-testhelper-my-suid-cat/testhelper-my-suid-cat.bin"

VPASSMAN_TESTHELPER_FIRST_USERNAME="${VPASSMAN_TESTHELPER_FIRST_USERNAME:=some_test_user1}"
VPASSMAN_TESTHELPER_SECOND_USERNAME="${VPASSMAN_TESTHELPER_SECOND_USERNAME:=some_test_user2}"
export VPASSMAN_TESTHELPER_FIRST_USERNAME
export VPASSMAN_TESTHELPER_SECOND_USERNAME

export VPASSMAN_TESTHELPER_FULLPATHOFPID_EXE_PATH="${VPASSMAN_PROJECT_BASE_DIR}/src-testhelper-insecure-fullpath-of-pid/testhelper-insecure-fullpath-of-pid.bin"

exec $*
